name: CI
on:
  push:
    branches: [master]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust toolchain
      run: rustup show

    - name: clippy
      env:
        BASEDIR: "."
      run: cargo clippy --target x86_64-unknown-uefi -- -D warnings
      continue-on-error: true

  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt install --yes make mtools parted
        rustup show

    - name: Build UEFI application
      run: make
